# http://www.appveyor.com/docs/appveyor-yml
os: Visual Studio 2017
version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

environment:
  matrix:
  - nodejs_version: "12"
    platform: x64
    
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test

cache:
  - node_modules -> package.json
